server:
  port: 8077

spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: task-tracker-email-sender

  mail:
    host: smtp.mail.ru
    port: 465
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
          starttls:
            enable: false
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: my-consumer-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
    properties:
      spring.json.type.mapping: >
        userCreated:io.roadmap.tasktrackeremailsender.dto.KafkaCreateUserMessage
#        ,other dto's
      spring.json.trusted.packages: "io.roadmap.tasktrackeremailsender.dto"